version: '2.1'
services:

    master:
        image: medmrgh/docker-locust:latest
        environment:
            - ATTACKED_HOST=${ATTACKED_HOST:-http://master:8089}
            - LOCUST_MODE=master 
        ports:
          - "8089:8089"
          - "5557:5557"
          - "5558:5558"
        volumes:
          - ./locust-scripts:/locust
          
    slave:
        image: medmrgh/docker-locust:latest
        restart: always
        depends_on:
            - master
        environment:
            - NO_PROXY=master 
            - ATTACKED_HOST=${ATTACKED_HOST:-http://master:8089}
            - LOCUST_MODE=slave
            - LOCUST_MASTER=master
        volumes:
          - ./locust-scripts:/locust
