version: 2

jobs:
  build_and_test:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/docker-locust
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Install requirements
          command: apk add curl
      - run: 
          name: Build docker image
          command: docker build -t medmrgh/docker-locust:test .
      - run: 
          name: Start locust
          command: >
            docker run --name standalone
            --hostname standalone -e ATTACKED_HOST=http://standalone:8089
            -p 8089:8089 -d medmrgh/docker-locust:test
      - run: 
          name: Test http response
          command: curl -I http://localhost:8089 | grep "200 OK"
      
workflows:
  version: 2
  build_run_test:
    jobs:
      - build_and_test

